### ISSUE TITLE
Broken for Django 5.1.x

### ISSUE THREAD

**Issue by dtcooper** [matthiask/django-user-messages#6]
Hi there,

I installed the latest version of `django-user-messages` for this GitHub repository, and obverse a broken migration on Django 5.1.x. If I revert back to Django 5.0.x it works file. I believe the error is due to [the removal a model's `Meta.index_together` option](https://docs.djangoproject.com/en/5.1/releases/5.1/#features-removed-in-5-1).

Here's my error,

```python-traceback
root@081059858a5c:/app# ./manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, constance, contenttypes, django_file_form, sessions, tomato, user_messages
Traceback (most recent call last):
  File "/app/./manage.py", line 24, in <module>
    main()
  File "/app/./manage.py", line 20, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.12/site-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.12/site-packages/django/core/management/base.py", line 459, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/management/base.py", line 107, in wrapper
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/management/commands/migrate.py", line 303, in handle
    pre_migrate_apps = pre_migrate_state.apps
                       ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/migrations/state.py", line 565, in apps
    return StateApps(self.real_apps, self.models)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/migrations/state.py", line 626, in __init__
    self.render_multiple([*models.values(), *self.real_models])
  File "/usr/local/lib/python3.12/site-packages/django/db/migrations/state.py", line 664, in render_multiple
    model.render(self)
  File "/usr/local/lib/python3.12/site-packages/django/db/migrations/state.py", line 957, in render
    return type(self.name, bases, body)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/base.py", line 143, in __new__
    new_class.add_to_class("_meta", Options(meta, app_label))
  File "/usr/local/lib/python3.12/site-packages/django/db/models/base.py", line 371, in add_to_class
    value.contribute_to_class(cls, name)
  File "/usr/local/lib/python3.12/site-packages/django/db/models/options.py", line 220, in contribute_to_class
    raise TypeError(
TypeError: 'class Meta' got invalid attribute(s): index_together
```

Thanks!

**Comment by matthiask** [comment]
Hi @dtcooper 

I have (fingers crossed!) already fixed that in 51b8151e8419c536d6d138b73d92cdd7889c7db9 but haven't made a release yet.

Can you test the current `main` version and report back if it works for you? That would be very helpful. I'm happy to upload a release then.

**Comment by dtcooper** [comment]
The current version (51b8151) is _currently_ broken... so I'm not sure the fix worked. In any event, cheers and thanks for the great package. :)

```
root@5b5789322fe9:/app# poetry add git+https://github.com/matthiask/django-user-messages.git

Updating dependencies
Resolving dependencies... (0.1s)

Package operations: 0 installs, 1 update, 0 removals

  - Updating django-user-messages (1.0.0 -> 1.0.0 51b8151)

Writing lock file
root@5b5789322fe9:/app# ./manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, constance, contenttypes, django_file_form, sessions, tomato, user_messages
Traceback (most recent call last):
  File "/app/./manage.py", line 24, in <module>
    main()
# ... long exception as above
    raise TypeError(
TypeError: 'class Meta' got invalid attribute(s): index_together
```

**Comment by dtcooper** [comment]
Perhaps you forgot to remove the migrations the new squashed migration replaces?

**Comment by matthiask** [comment]
Yes indeed. I have never squashed migrations before (only deleted them outright). I think it works after deleting the old migrations and have run basic tests with a really old project. I'll upload a release if the tests pass.

**Comment by matthiask** [comment]
Fixed in 1.1. Thanks!

**Comment by dtcooper** [comment]
Thanks @matthiask!

**Comment by dtcooper** [comment]
I confirm the fix works! Will you be publishing to PyPI? :)

**Comment by matthiask** [comment]
Oh, I shouldn't work late in the night ...

Now the upload has worked without an error :-D
